### ISSUE TITLE
Asciidoc is broken

### ISSUE THREAD

**Issue by martin-g** [nfrankel/kaadin#2]
The links at https://github.com/nfrankel/kaadin/blob/master/Components.adoc#native-button are broken.

**Comment by nfrankel** [comment]
Yes, I know... "it works on my machine"

I have to understand how Github generates HTML from Asciidoctor files. Dan Allen pointed me to sub=[macros] but my Asciidoctor skills are not good enough to understand what that means.

If you have any clue, I'll be happy to accept PR. And thanks for your interest in all cases.

**Comment by nfrankel** [comment]
I've reworked the documentation and broken it down in a very simple [README](https://github.com/nfrankel/kaadin/blob/master/README.adoc) and a full-fledged [Github Page site](https://nfrankel.github.io/kaadin/).

**Comment by martin-g** [comment]
Perfect!
