### ISSUE TITLE
won't build - environment issue?

### ISSUE THREAD

**Issue by carljmosca** [nfrankel/kaadin#3]
[ERROR] /Users/moscac/dev/kaadin/kaadin-core/src/test/kotlin/ch/frankel/kaadin/interaction/MenuBarTest.kt: (58, 55) Type mismatch: inferred type is MenuBar.Command but (MenuBar.MenuItem) -> Unit was expected
[ERROR] /Users/moscac/dev/kaadin/kaadin-core/src/test/kotlin/ch/frankel/kaadin/interaction/MenuBarTest.kt: (71, 51) Type mismatch: inferred type is MenuBar.Command but (MenuBar.MenuItem) -> Unit was expected
[ERROR] /Users/moscac/dev/kaadin/kaadin-core/src/test/kotlin/ch/frankel/kaadin/interaction/MenuBarTest.kt: (89, 55) Type mismatch: inferred type is MenuBar.Command but (MenuBar.MenuItem) -> Unit was expected

**Comment by nfrankel** [comment]
It's not an environment issue, that's my mistake in one of the refactoring. Should be fixed now, could you please confirm?

**Comment by carljmosca** [comment]
Yes, thank you it builds OK now.  Will take a closer look this weekend.

**Comment by nfrankel** [comment]
Thanks for your interest _and_ your feedback.
